#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-docutils
Version  : 0.14
Release  : 49
URL      : http://pypi.debian.net/docutils/docutils-0.14.tar.gz
Source0  : http://pypi.debian.net/docutils/docutils-0.14.tar.gz
Summary  : Docutils -- Python Documentation Utilities
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause GPL-2.0 Public-Domain Python-2.0
Requires: deprecated-docutils-bin = %{version}-%{release}
Requires: deprecated-docutils-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3

%description
=======================
=======================
:Author: David Goodger
:Contact: goodger@python.org
:Date: $Date: 2017-08-03 11:03:32 +0200 (Do, 03 Aug 2017) $
:Web site: http://docutils.sourceforge.net/

%package bin
Summary: bin components for the deprecated-docutils package.
Group: Binaries

%description bin
bin components for the deprecated-docutils package.


%package legacypython
Summary: legacypython components for the deprecated-docutils package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-docutils package.


%package python
Summary: python components for the deprecated-docutils package.
Group: Default

%description python
python components for the deprecated-docutils package.


%prep
%setup -q -n docutils-0.14

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554314629
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pushd test ; python2 ./alltests.py ; popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
## install_append content
cp %{buildroot}/usr/bin/rst2man.py %{buildroot}/usr/bin/rst2man
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rst2html.py
/usr/bin/rst2html4.py
/usr/bin/rst2html5.py
/usr/bin/rst2latex.py
/usr/bin/rst2man
/usr/bin/rst2man.py
/usr/bin/rst2odt.py
/usr/bin/rst2odt_prepstyles.py
/usr/bin/rst2pseudoxml.py
/usr/bin/rst2s5.py
/usr/bin/rst2xetex.py
/usr/bin/rst2xml.py
/usr/bin/rstpep2html.py

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)
